apiVersion: apps/v1
kind: Deployment
metadata:
  name: helidon-quickstart-se-deployment
spec:
  selector:
    matchLabels:
      app: helidon-quickstart-se
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helidon-quickstart-se
    spec:
      containers:
      - name: helidon-quickstart-se
        image: namsing1/helidon:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
